services:
  - type: web
    name: browseiq-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 8001
    plan: free 