services:
  - type: web
    name: browseiq-backend
    env: python
    buildCommand: pip install -r backend/dex-mcp-upstream/requirements.txt
    startCommand: python backend/dex-mcp-upstream/main.py
    envVars:
      - key: PORT
        value: 8001
    plan: free